name: nanograv-edr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - astropy
  - tqdm
  - pip
  - pip:
      - enterprise-pulsar
      - enterprise_extensions
      - pint-pulsar
