name: camilo-edr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pip
  - pip:
      - pint-pulsar
      - enterprise-pulsar
      - enterprise_extensions
      - libstempo
      name: edr-gw
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - h5py
  - jupyter
  - pip
  - pip:
      # gwpy es opcional; si te dio problemas, puedes comentar esta l√≠nea
      - gwpy
