name: edr-gw
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - h5py
  - jupyter
  - pip
  - pip:
      - gwpy   # si llegara a dar problemas, luego se puede comentar esta l√≠nea
